### ISSUE TITLE
knowing which patients you're making changes to

### ISSUE THREAD

**Issue by tom-parks** [openhealthcare/elcid#1359]
Having just gone through the Heroku test stage for the first time, I find it all too easy to click and make changes to the wrong patient (e.g. discharge). I would like to see the patient's name and hospital number at the top of all the modal boxes.

**Comment by GabPoll** [comment]
conceptually, i think this is a good idea. Would be a clinical risk win.

**Comment by pacharanero** [comment]
This issue pervades many hospital systems I've used. If it can be ameliorated in OPAL/Elcid, that is a win

**Comment by davidmiller** [comment]
Hi Tom, 

My understanding was that we have the patient name in modal headers for just this reason.

It looks like at some point we've lost this from the discharge and 'change teams' modal headers - was there anywhere else specifically that you found yourself unsure what patient you were making changes to ?

With regards hospital numbers - does it actually make it safer to display the hospital number as well ?
(Because if we're adding hospital number to name then we should do so consistently.)

**Comment by davidmiller** [comment]
This was deployed to production last week so closing this one - if we do want to put hospital numbers in everywhere let's have that in a new ticket.
