### ISSUE TITLE
Non-OPAT Fields should not appear in OPAT episode Single Patient View

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#249]
If: Location Category equals OPAT
Then: Single Patient View should not display many of the non-OPAT fields
(Clinical advice, to-do, general notes)

I would leave Travel in the OPAT Single Patient view as it may be relevant

But clinical advice is replaced by OPAT-Review and To-Do/General Notes are replaces by Outstanding Issues

see #248

**Comment by GabPoll** [comment]
Apologies for dredging up an old issue, but we may have overdone it here. 

Currently, there are OPAT patients that are also discussed on elCID ortho round. Clinical advice added on micro-ortho list, but then on single patient view this is NOT visible at all. 

Short term solution is to display clinical advice on OPAT pt single pt view. However, there is a risk that the two advice boxes (OPAT r/v & clinical advice) are on completely different part of the page, and would need clinician to scroll between the 2 to compare. This is still preferable to current situation of not being able to see clinical advice at all (unless in OPAT clinic they know to look up micro-ortho list - not a solution).

In medium term, i suspect @davidmiller suggestion to #469 is a good one - i.e. OPAT r/v becomes a variant of clinical advice.

Personally, i think we need the short term fix of showing clinical advice, and then we need a discussion on a more permanent solution. Ping @michaeledwardmarks

**Comment by davidmiller** [comment]
### Digression for context: 

@GabPoll so, this is a bit subtler because of e.g. #531 - wherein we figured that the OPAT episode would be a distinct episode from an inpatient episode.

Specifying fields that are synced for concurrently open episodes has a lot of complexity and probably merits it's own ticket - not to mention a wider discussion / consideration than this use case (OPAT)!

Once we fix #586 then the user may navigate to the other inpatient episode from detail view - where CA would be entered.

Perhaps one of the things we need is a way to alert the user to the fact that there are multiple concurrent open/active episodes when that occurs ?

### Meanwhile, back at this issue:

We can absolutely add Clinical Advice to the OPAT Detail View.
When an inpatient episode is "imported" to OPAT, CA already entered will be transferred to the OPAT episode.

That's a quick fix if we think it's worth doing?

**Comment by GabPoll** [comment]
Very interesting @davidmiller 
Good points. I agree with:
- Fixing #586 
- Alerting re multiple active episodes

Short term fix i think is a good one (can be at the bottom of OPAT list as that would detract the least, but "it's there". Key is it happens both ways to scenario mentioned. At the moment we have pt on OPAT who is then, a couple of weeks later, added to micro-ortho list, and clinical advice added there (all as an outpatient). So perhaps we keep OPAT as the outpatient episode, but if patient added to micro-ortho, just offer the opportunity to write some clinical advice that is separate to OPAT advice, and that is visible on single patient view. All part of the same episode.

**Comment by davidmiller** [comment]
> keep OPAT as the outpatient episode, but if patient added to micro-ortho, just offer the opportunity to write some clinical advice that is separate to OPAT advice, and that is visible on single patient view. All part of the same episode.

Not entirely sure I follow you here, but this seems to be suggesting that we either have two open concurrent episodes of care which have synchronised advice, or that the Ortho list has both inpatients & outpatients? 

Neither of those are straightforward !

I may be confused, but if a Micro Ortho doctor is giving advice on an OPAT patient who is an outpatient, why don't we add CA to OPAT detail view, and then they do that from the OPAT list via the details screen?

**Comment by GabPoll** [comment]
Yes, Ortho list contains both inpatients an outpatients. This actually seems to work without a problem - it pulls in info from any episode (inpatient or outpatient) and populates list accordingly. Crucially, Ortho does not require a new episode. Just additional documentation of whatever episode the patient is in.

As you say, the simplest solution is to add CA to OPAT detail view. That way at least the information is visible. Do you think you could do this for 0.4? Otherwise the utility of the micro-ortho round is partly limited at present. Thank you.

**Comment by davidmiller** [comment]
So, the discussion with #531 suggests that there are problems with having OPAT episodes on other lists - I'm fairly sure that we've had to go in and manually separate them.

The decision by me & @michaeledwardmarks was that adding to non OPAT lists would require a separate episode - if that's changed, then we need to discuss that  ! :) 

Probably in the other ticket though...

Adding CA to OPAT detail is trivial, and I'm sure we can do that.

My question above was mostly "If micro ortho are giving advice on an OPAT patient, why don't they use the OPAT list" ?

**Comment by michaeledwardmarks** [comment]
Personally I think the answer here is not to show Non-OPAT fields in OPAT-episodes but rather 
- [ ] Alert user that person has an OPAT episode
- [ ] Work out hot to better curate/manage a list/system like Micro-Ortho where the clinical service manages both OPAT and non-OPAT patients

**Comment by davidmiller** [comment]
What's the outcome of this discussion - anyone ? 

Is this ticket actionable ? :D

**Comment by michaeledwardmarks** [comment]
I think nothing actionable.
Close.
We should in future think a little bit about lists like Micro-Ortho which in ideal world would blend episode types.....needs some thought.
