### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#410]
Paginate the search page
Paginate the lists

FILTER list should ideally work across pagination - e.g by name and number

**Comment by davidmiller** [comment]
This seems to be significantly less of a problem due to speed enhancements elsewhere.
e.g. the 100+ MH list is manageable with 0.4.

Move to close and re-consider in a future performance sprint if this turns out to be where the best gains are.

**Comment by GabPoll** [comment]
i think we still need to paginate the search page -currently shows 1-10 of 15, but can't see the other 5.

Lists not important - agree fixed by supersonic 0.4 change.

**Comment by davidmiller** [comment]
Sooner or later we're going to need to paginate the list - one use case for example is research studies who will basically never discharge patients.

**Comment by davidmiller** [comment]
We should paginate sooner than later.
It's a real problem for e.g. RidRti

**Comment by davidmiller** [comment]
I'm closing this again - the original search pagination works, and it's a long time since this was noted as an issue for actual users... 

(Paginating lists is a little tricky for e.g. also doing filters quickly.)

I also think there are not really many lists with lots of patients where this would really be an issue, and that we've improved the speed of lots of pieces of the system significantly since Nov '15
