### ISSUE TITLE
Clinical advice entry - save as draft / minimise

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#431]
This is an annoyance introduced by fixing #60 .

Now cannot come in and out of a clinical advice field (e.g. to check other results) and then resume clinical advice where left off.

Best technical solution to be suggested by @davidmiller

**Comment by GabPoll** [comment]
@davidmiller i presume this is not a trivial solution (that's ok). Would temporary reversal of #60 be a good/easy short-term fix? Vanya seemed to find it pretty irritating that I suspect he'd think so. Thoughts also from @jonnylambourne please on this given that OPAT v1 at present likely to launch with this issue still open.

**Comment by jonnylambourne** [comment]
as above, agree that this would be neat
don't think it should delay go-live of elCID-OPAT, and am happy for it to go onto the 'to do' list for OPAT v2 (or v1.1..)

**Comment by davidmiller** [comment]
User perspective:
- [ ] Entries can be saved as draft
- [ ] They will stay as draft for 3 hours or
- [ ] They will stay as draft until the user clicks "Save & Lock"
- [ ] Draft entries will be editable
- [ ] Re-editing resets the draft timer
- [ ] Draft entries will be visually distinct

Technical steps proposed: 

- [ ] Add created & modified timestamps to the core subrecord base classes (in model scope rather than reversion scope)
- [ ] Add a "locked" field to such models as we feel should be draftable
- [ ] Create a "Draft" Angular filter for display templates that shows the display difference (adds an Icon?)
- [ ] Update modal templates to have new action buttons, and switch the display logic to "Is new/draft?"

**Comment by michaeledwardmarks** [comment]
+10

**Comment by GabPoll** [comment]
agree, all sounds correct @davidmiller

**Comment by davidmiller** [comment]
Given that we're now having clinical advice orientated patient detail views, I suspect that this is now entirely moot - move to close ?

**Comment by GabPoll** [comment]
yep, no longer needed once implement new patient detail view / haem WR (will need to give it a name - Clinical Review view?)
