### ISSUE TITLE
OPAT test version - Antimicrobials

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#500]
Amtimicrobials
On Heroku app test version - When I add an antimicrobial from the ‘OPAT referral’ and ‘OPAT current’ screen, ‘ceftriaxone 2g’ displayed on the menu screen as ‘ceftriaxone 2D’.  When I add a antimicrobial in the ‘OPAT follow up screen, ‘ceftriaxone 4g’ displayed as ‘ceftriaxone D’.  Teicoplanin 600mg displayed as ‘Teicoplanin 10D’.  I can't remember this happening with the UCLH test version.  There is something odd happening. 

When I add a new patient and then add new antimicrobials from the ‘referrals’ screen, the allergies do not appear at the top of the box (this happens even if I entered a new allergy and then entered a new antimicrobial).  This doesn’t seem to happen when I add a new antimicrobial from the ‘current’ or ‘followup’ screen.    

On Heroku app, the field for ‘Delivered by’ is missing, but this is present in the UCLH test version.

**Comment by michaeledwardmarks** [comment]
Just checking through these

- The D after the name of the antimicrobial is the number of days since the entered start date. This is what was requested by OPAT team.

-  When I add a new patient and then add new antimicrobials from the ‘referrals’ screen, the allergies do not appear at the top of the box: Can't Replicate - works fine for me

- Delivered for field: Can't replicate - present on both versions for me

- [ ]  Agree that dose doesn't display on OPAT antimicrobials and that this is Incorrect
Should be:
Drug Dose NumberDays
e.g
Co-Amoxiclav 1.2G D4

**Comment by michaeledwardmarks** [comment]
Just to say I checked on elCID-TEST and I'm not getting the issue with allergies - they appear in antimicrobial modal for me.

So I think outstanding issue here is about formatting and display of dates as above.

**Comment by 7575colli** [comment]
The bug that i described above was from Heroku app

**Comment by michaeledwardmarks** [comment]
@7575colli @davidmiller 
Ok I have investigated further.
This bug is restricted to Detail view

Patient has allergy
- open anti-microbial modal on the List view: Allergy displays (CORRECT)
- open anti-microbial modal on Detail view: Allergy does not display (INCORRECT)

So the do points are:
- [ ] Make allergy display in the OPAT Review and Antimicrobial modals for OPAT patients on Detail view as well as list view

- [ ] Formatting of OPAT antimicrobials
Should be:
Drug Dose NumberDays
e.g
Co-Amoxiclav 1.2G D4Formatiing

**Comment by 7575colli** [comment]
On the UCLH test version, I just had the following issues with antimicrobial field:

1) No look up list for 'delivered by'
2) No look up lists (and unable to enter any free text) in 'Adverse events' and 'Reason for stopping' fields

**Comment by 7575colli** [comment]
Not essential to implement now but i think that there is a good argument for making the allergy field appear even when the pt has no allergies (as you would when you look at a drug chart).  This way, the user is prompted to see that the allergy field hasn’t been completed, there are no allergies or there is a confirmed allergy.

**Comment by michaeledwardmarks** [comment]
The lookup lists issue is the same one everywhere - we need to import these over as already mentioned.

**Comment by 7575colli** [comment]
Also not essential to implement now - but its a shame to have to move between the detailed screen and general screen to see how many days the pt has been having antibiotics for.

**Comment by michaeledwardmarks** [comment]
Agree.
 - [ ]Formatting of Antimicrobials should be consistent between List and Patient Detail View (Dose needed on BOTH list and detail view, Number of Days already shows on list view but needs to be added to Detail View)

**Comment by davidmiller** [comment]
@michaeledwardmarks Having the allergies display on both will either:

* Come on Monday if we add it to all modal
* Come (In a better way) as part of the 1.0 release one way or another.

It's non-critical so move to bump if we're not putting it everywhere.

**Comment by michaeledwardmarks** [comment]
@davidmiller 
This doesn't seem to have worked.
I currently get
- Day count on list view, but no dose
- Dose on detail view, but no day count

Thoughts?

**Comment by davidmiller** [comment]
It's now deployed to elcid-search (Yes I do mean elcid-search)

**Comment by michaeledwardmarks** [comment]
Ok this is all done except the allergy thing which I think we are holding (anticipate some feedback on that but if better to fix more generally then fine by me).
