### ISSUE TITLE
OPAT test version - Diagnosis/issues

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#504]
Diagnosis/issues:
If I add and then delete a diagnosis/issue, the date still appears in the ‘lists’ field.

**Comment by michaeledwardmarks** [comment]
Are you opening the modal and deleting the dignosis or actually deleting the entry from list view - i.e highlighting it and clicking delete.

If you delete the diagnosis from list view rather than simply deleting it inside the modal then the date disappears - because you have actually deleted the entry. 

Hope that makes sense.

**Comment by davidmiller** [comment]
As a meta-issue we should look at better delete-discovery for version 1.0, unlikely to happen before full-scale detail & list overhaul though :)
