### ISSUE TITLE
As a User I would like to (mouse) click or tab to select a lookuplist item 

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#518]
I have no idea how to describe this, but try the following

Add a new patient and in gender section type "m". You get option female, indeterminate and male (OK). Choose male with the mouse, then get second look up list with male and female.

Is this looking up a second list?

**Comment by davidmiller** [comment]
@GabPoll There's definitely only one list. 

It may be that there's a bug with the lookuplists in general. 

I suspect that selecting an option which is a complete subset of another option is not a common occurrence - e.g. male is entirely contained within female.

It may well be that we should do something else when you click on an item in a lookuplist - e.g. act like tab.

Short term, can you press tab instead of click ? :)

**Comment by GabPoll** [comment]
Thanks @davidmiller - might have to change name of ticket. Issue persists if you press return on keyboard on male. I think your "male is within female" issue is correct.

Tab would be good solution i think and personally, a GUI improvement throughout elCID. I.e. when lookup list turns up, i can't press tab on desired option and it moves onto next field. This is common procedure on other websites in my experience and would prob solve this issue.

Low priority for now, i appreciate that, but just documenting for future.

**Comment by davidmiller** [comment]
With Gender specifically, I've switched the input type to be a dropdown rather than FT + Lookuplist. 

If there are no other instances of this anyone can find/think of, I move to close for now ?

**Comment by GabPoll** [comment]
i have preference to tab & select over pressing return. so far looks like i'm alone. Issue closed.
