### ISSUE TITLE
Adding patients who have an open OPAT episode

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#531]
Present behaviour

1) Adding to OPAT from other list == Correct
- On OPAT list 
- Add patient for patient with current inpatient episode
- Choice between Import or New Episode 
- Episode created

2) Adding to other list from OPAT == incorrect
- On Inpatient list
- Add patient for patient with current OPAT episode
- elCID Tags the OPAT episode to the inpatient list

Desired behaviour for number 2
- Create new inpatient episode - distinct from the OPAT episode
- At present I suggest import nothing (can review)

NB: Behaviour number two would also be the correct behaviour for Walk-In
e.g patient on walk-in, add to inpatient list should create new distinct episode

**Comment by michaeledwardmarks** [comment]
Note that in fact behaviour two occurs even if the OPAT episode is in the past.
So Archived Episode modal offers OPAT episodes (regardless of status) to be tagged/re-opened on Inpatient lists

**Comment by michaeledwardmarks** [comment]
I don't think OPAT episodes should appear in the Archived Episode modal at all in fact.

**Comment by michaeledwardmarks** [comment]
This is now occurring in the wild and causing problems

**Comment by michaeledwardmarks** [comment]
@davidmiller 
I assume that the proper episode categories changes should help with this?

Several real-world issues this week which make me think an interim (pre-0.4) fix for this and #555 should be considered soonish.

**Comment by davidmiller** [comment]
From @GabPoll : 

> Ortho list contains both inpatients an outpatients. This actually seems to work without a problem - it pulls in info from any episode (inpatient or outpatient) and populates list accordingly. Crucially, Ortho does not require a new episode. Just additional documentation of whatever episode the patient is in.

**Comment by davidmiller** [comment]
### What is an elCID list ?

A list in elCID is a group of patient episodes that have been associated with a particular team.
Episodes have different types - e.g. an OPAT episode is not the same as an Inpatient episode is not the same as a Research episode.

### What happens when you add an episode to another list?

Traditionally, the episode was just associated with two teams. When all we have is one episode type (e.g. inpatient) this works just fine.

With the addition of the OPAT and Research modules, we introduced the concept of fully fledged episode categories - different types of episode which have different actions and flows associated with them, as well as different display properties.

When a patient moves from one category to another, we open a second concurrent episode of the second category. We import the episode details from the first episode at the point of creation, but do not subsequently synchronise them.

### What is this ticket about ? 

This ticket notes that this was not fully implemented - that it was only implemented when going from inpatient -> OPAT, but not the other way around. 

Inpatient teams being able to associate themselves with outpatient (OPAT) episodes causes many unintended consequences, particularly around the display of OPAT specific fields and available "next step" actions in the OPAT patient 

### What was the plan for this ticket?

My understanding was that we would associate each list with an episode category, and when adding a patient with an open episode to a list, we would either just associate it (e.g. adding an ID Inpatient episode to Virology) or create a new episode (e.g. adding an ID Inpatient episode to a Research Study list).

If we want to have lists with multiple episode categories this greatly complicates the logic about what to do when a patient is added to a list. e.g. 

How would one figure out whether to associate or create a new episode? 
For all possible combinations?


### What is the actual desired behaviour? 

This is now not clear to me at all ! 
I'm not sure we've mapped the space or understood the problem / needs!

I'm going to open a new OPAL ticket to consider episode categories and their relationship to lists again at a global level for the entire system - as I don't think this ticket is really the right place ;) 


### Specifically regarding Micro Ortho 

My feeling is that we have expanded to the Micro Ortho round without really having a proper Discovery Phase. I don't feel that I understand the User Needs particularly at all - and my incomplete understanding is based on a couple slack conversations !

Software is hard :)

**Comment by michaeledwardmarks** [comment]
@GabPoll @davidmiller 

I think that we need to keep OPAT and Non-OPAT episodes distinct - because the interaction between them already causes trouble and we have seen this issue in the live version, causing episode clashes, data problems etc.

I agree with @davidmiller that lists should constitute one type of episode for the reasons he outlines above. Specifically I agree with the following:

"My understanding was that we would associate each list with an episode category, and when adding a patient with an open episode to a list, we would either just associate it (e.g. adding an ID Inpatient episode to Virology) or create a new episode (e.g. adding an ID Inpatient episode to a Research Study list)."


As this is a generic ticket about underlying behaviours I suggest we move the Micro-Ortho Discussion to a specific ticket

**Comment by davidmiller** [comment]
Note: This ticket must also figure out what to do with the "Teams" modal for services that do not have direct add/remove teams but actions to progress through a service.

**Comment by davidmiller** [comment]
Patients with an open OPAT episode will now not be multi-tagged to inpatient lists!

(Deployed to elcid04test

**Comment by michaeledwardmarks** [comment]
@davidmiller 
When I added Brenda Benson to Tropical list (whilst she was on OPAT-Current) I got a new episode where Category==OPAT.
On patient details view for both the episode number == 3 which leads me to conclude that the OPAT episode has still been tagged to an inpatient list

**Comment by davidmiller** [comment]
@michaeledwardmarks Good spot ! 

Only partially implemented because of the two admission routes for inpatients (Presenting Complaint & Not Presenting Complaint). Should now be fixed.

Deployed to elcid04-test.

**Comment by michaeledwardmarks** [comment]
Is indeed!
