### ISSUE TITLE
Make growler info a clickable link

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#622]
Had a look and can't seem to find a ticket for this.

When growler says "pt moved to Doctor list", would be nice for Doctor list to be a hyperlink that takes you there. Perhaps not absolutely necessary for triage nurse to go to doctors' list, but may be useful in other settings, like OPAT referrals, etc...

**Comment by davidmiller** [comment]
@GabPoll So, I think that this is only really relevant for services where lists are stages within a service.

And I agree with what I think is the underlying thought here - that the switch from tabs to dropdown for teams is a trade off and has come slightly at the expense of what was previously very natural Left to right movement through a service. 

In fact I was discussing just that earlier in the week.

This ticket specifically is very much a solution before stating the problem though !

**Comment by GabPoll** [comment]
yes and no @davidmiller . I don't want us to waste time on this pre-0.4 release, but this is not just about stages of service. It's about navigation and keeping track of patients, irrespective of the tab or drop down menu.

"I'll add this patient on the Ortho list". Done. "Let's see who else is on the ortho list"

I propose to do nothing with this, keep it open but see if it comes up in future discussions.

**Comment by davidmiller** [comment]
It's been a while since this came up... this mostly happens on Opat / Walkin where people move across what are now tabs in the service.

My sense is that now we have those tabs we probably don't need links in the growl. 
Even then, navigation in transitory notifications that close themselves seems like a bit of an anti-pattern to me - just make the navigation better !

Closing for now, but we can think again if we need to.
