### ISSUE TITLE
List view page shouldn't scroll overall

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#700]
I can't tell if this is old or new since fix to #682.

In essence, the whole page below the top banner scrolls and it shouldn't. Is that enough detail? Go to Micro ortho and scroll page - it does and it shouldn't. It goes away if i zoom out of firefox, but then font too small for me.

Anyone else notice this? Ping @michaeledwardmarks @fredkingham @davidmiller

**Comment by michaeledwardmarks** [comment]
Yes I get on FF.
initially the list panel scrolls correctly #682 with the headers and the sidebar staying in place, but as you keep scrolling down the list eventually the whole page scrolls.
I think we can close this as part of same as #682 @GabPoll ?

**Comment by GabPoll** [comment]
@michaeledwardmarks slightly disagree. This has crept in prob because of #682, but it's a separate issue. The page scrolls even when list is not long enough for it to scroll itself, like micro ortho for example.

@fredkingham & @davidmiller to be honest, play it as you wish. Personally, i'd close #682 and leave this open, but if you want to merge or whatever, i don't mind. Most important thing is that @michaeledwardmarks also sees this behaviour so it's real. Thank you for checking.

**Comment by michaeledwardmarks** [comment]
Ok. Yes - see what you mean.
I'll shut #682

**Comment by fredkingham** [comment]
yep, so at the moment only the table scrolls if you're mouse pointer is within the boundaries of the table and there is enough space below the table to scroll the table only will scroll, otherwise the window scrolls.

This kinda make sense as really the table scrolling is the most important part, in the previous version of #682 if the window scrolled rather than the table scrolled, the headers went out of view so I've fixed this now at https://elcid04-test.herokuapp.com/#/list/opat/opat_referrals. I'll merge this on to 0.4.2 if there are no objections.

The wider issue of the table scrolling vs the window scrolling remains. If we change this behaviour the add a patient button will scroll off, I'm not sure if this is wanted or not.

**Comment by michaeledwardmarks** [comment]
Hi @fredkingham 
So I think what you have just done is an improvement with the table headers always fixed.
Personally (and I think @GabPoll agrees) I think the sidebar and add patient buttons should always be visible.
So i like screen shot 1 but not 2.
![screen shot 2015-09-02 at 13 35 26](https://cloud.githubusercontent.com/assets/4578105/9631253/97931100-5177-11e5-84c9-9530915816bb.png)

![screen shot 2015-09-02 at 13 37 07](https://cloud.githubusercontent.com/assets/4578105/9631281/c58082aa-5177-11e5-9f7b-0e72ec6c634b.png)

**Comment by fredkingham** [comment]
ah ok gotcha, we want everything fixed, that makes sense

**Comment by michaeledwardmarks** [comment]
yes the only thing that should scroll is the patient records.

**Comment by GabPoll** [comment]
New / related issue with new patient highlighting feature. 
If keep clicking down on keyboard, the highlighting goes off the page, whereas the bottom row should remain highlighted and the list scroll to enable that.
