### ISSUE TITLE
Alert investigation results panel at the top to be collapsible

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#738]
Flip headed arrow.
Otherwise will get very long and push everything else down

**Comment by davidmiller** [comment]
So, this would be the only place in the application where anything is collapsible ! 

We currently use either scrolling  or "don't show it" as a way to show more information :)

Can we discuss some alternative strategies in more detail - e..g I'd like to close this, do the other outstanding MH project tickets, and then revisit starting from user needs not solutions so that we can evaluate other options fully !

**Comment by GabPoll** [comment]
@davidmiller that is fine with me. Idea came in d/w @fredkingham so perhaps discuss with him first before closing. I'm happy with building MH thing first and leave this out in first iteration (or at least at first proper demo)

**Comment by davidmiller** [comment]
@fredkingham was looking over my shoulder as we typed ! :) 

OK - let's do the things that are obvious and then see where we're at
