### ISSUE TITLE
On advice view, allergies can be displayed inline

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#740]
to save vertical screen space

**Comment by fredkingham** [comment]
@gabpoll do we actually want this?

I think we suggested it because we were worried it would take up too much room at the top of the screen, but really its the alert organisms that will take up all the space right? We don't expect to many allergies.

By not changing it we keep it consistent with the patient details view (and I consistency :))

**Comment by GabPoll** [comment]
Very happy to not do this then, for reasons you state. I think you'd suggested so was accommodating, but bulleted list of allergic antibiotics is easier to spot anyway, so let's stick with what we have at the moment.
