### ISSUE TITLE
When logging back in I'm not taken to the list I was last looking at

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#743]
Di in Walk-In reports that she normally gets taken to the Immune-Inpatient list not the Walk-in-Triage list when she logs in.

**Comment by davidmiller** [comment]
Can you reproduce that ?

**Comment by davidmiller** [comment]
I suspect that we might like to be able to set a custom home page on the user profile.

Going to the first list will increasingly be not the correct thing to do.
/cv @fredkingham

**Comment by michaeledwardmarks** [comment]
I can't reproduce myself but she demonstrated it to me.
Seemed random. she logged on/off a few times and it happened sometimes.

Agree defining a correct first page for certain users would be very sensible

**Comment by GabPoll** [comment]
Defining correct first page by user seems like a good suggestion.

Could I also pitch an alternative solution that I may have mentioned elsewhere. Could we make the List button at the top also a clickable team drop down (just like current team drop down). So that the first page after login is actually blank with just the ribbon at the top. The user then selects the team they want to see list of. Prevents loading time of a list that may be either unwanted (e.g. Vanya-type people won't want to see a list) or a wrong list as in this instance. I accept downside is one extra click, but you then ensure it always takes you where you want to go.

**Comment by davidmiller** [comment]
@GabPoll so, I'm generally of the opinion that dropdown menus are in general a major [Anti Pattern](https://en.wikipedia.org/wiki/Anti-pattern) :)

I'd need lots of convincing - and I'd want to do it consistently for everything if we did!

**Comment by michaeledwardmarks** [comment]
I have to say I'm not super keen on the extra-screen approach.

**Comment by GabPoll** [comment]
happy to discuss further, but @davidmiller we already have a teams drop down, so i wouldn't actually be changing anything in terms of the UI, just changing where this behaviour occurs.

@michaeledwardmarks agree would be an extra screen, but it would also load quicker (i.e. not loading any list at first login is faster) and it would always be correct (i,e. we don't have to create more and more rules guessing what people want to be the first thing they see when they log into elCID)

**Comment by michaeledwardmarks** [comment]
True but for me the issue is people like nurses - they don't like drop downs as not keen on computers(!) - they just want the correct page to load - hence why a default view is better IMO.

**Comment by GabPoll** [comment]
If people don't want drop downs, that's fine by me. Quite how that's related to not being keen on computers, I don't know. They're everywhere!

Anyway, this is an idea that worth mentioning. We can be guided by the users' wishes. I'm not too fussed exactly what we decide to go with, as long as users happy and @davidmiller happy with solution too.

**Comment by davidmiller** [comment]
@fredkingham I think this was fixed in 0.6.3 by a version bump in Angular ?

**Comment by davidmiller** [comment]
This has been implemented now with 3c3b601
