### ISSUE TITLE
does discharge with follow-up set discharge date

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#774]
Should be true for
Discharge
Discharge with follow up
Transferred
Deceased

This affects DLW 
@michaeledwardmarks to do.

**Comment by michaeledwardmarks** [comment]
As far as I can see these all set discharge dates on david-staging.
But it's very confusing because when you select discharge with follow-up the location field still displays "Inpatient" not "Follow-Up" I believe that is flagged elsewhere.

@davidmiller could you take a look also because I think you might have thought that some of these didn't set discharge dates and hence might have been the reason for someone not being on DLW
