### ISSUE TITLE
Growler background should be a different colour

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#856]
Light green on slightly darker green (when on episode view) is not a good look in my opinion.

**Comment by davidmiller** [comment]
I know what you mean...

The issue is more general - using green / red to signify success/warning or yes/no is problematic when you're also using them for navigation & as a primary colour... 

Because it's not clear what to use instead for signifying success/warning/etc :)

Honestly, unlikely to look at this before the rest of the backlog - I'm going to close for now, the answer is v. possibly "Use different primary / nav colours"...
