### ISSUE TITLE
Clinical Advice - should we mandate a when timestamp?

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#904]
Currently the user can delete the date/time.

We capture the timestamp that the entry was created, and can use that as a proxy for ordering purposes, but should we do some validation to force the user to have a value for date/time advice given?

Thoughts @michaeledwardmarks @GabPoll ?
(This has happened very occasionally)

**Comment by GabPoll** [comment]
i think we can't expect users to always enter date and time - especially within fixed fields. The current arrangement defaults to the time CA being written - i thought that was a good solution. Preventing it being edited once saved is fine by me.

We could however, prevent a null entry - so that a clinician can change the date and time advice was given, if it was a retrospective entry, but not then change it. Perhaps a locking time lag as previously described for CA?

**Comment by davidmiller** [comment]
@GabPoll Hmm, that wasn't quite what I was suggesting :) 

I'm not sure locking is a great idea, what I mean is that perhaps you shouldn't be able to save a Clinical Advice entry with _no_ date or time.

(At the minute you can just delete the values and save - this presents issues for ordering.)

I think you should continue to be able to edit the date time fields - these are separate from the created / updated timestamps we save (these are hidden and never user-editable), which gives us a separate record for audit trail purposes.

**Comment by davidmiller** [comment]
Closing this assuming that if nobody disagreed with my last comment since Jan '16 they're not about to start :D
